// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocumentById(arg1) {
  return window['go']['ipc']['Channel']['GetDocumentById'](arg1);
}

export function GetDocuments() {
  return window['go']['ipc']['Channel']['GetDocuments']();
}

export function RequestAddArea(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestAddArea'](arg1, arg2);
}

export function RequestAddDocument(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestAddDocument'](arg1, arg2);
}

export function RequestAddDocumentGroup(arg1) {
  return window['go']['ipc']['Channel']['RequestAddDocumentGroup'](arg1);
}
