// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1) {
  return window['go']['ipc']['Channel']['CreateNewProject'](arg1);
}

export function GetAllLocalProjects() {
  return window['go']['ipc']['Channel']['GetAllLocalProjects']();
}

export function GetAreaById(arg1) {
  return window['go']['ipc']['Channel']['GetAreaById'](arg1);
}

export function GetCurrentSession() {
  return window['go']['ipc']['Channel']['GetCurrentSession']();
}

export function GetCurrentUser() {
  return window['go']['ipc']['Channel']['GetCurrentUser']();
}

export function GetDocumentById(arg1) {
  return window['go']['ipc']['Channel']['GetDocumentById'](arg1);
}

export function GetDocuments() {
  return window['go']['ipc']['Channel']['GetDocuments']();
}

export function GetProcessedAreaById(arg1) {
  return window['go']['ipc']['Channel']['GetProcessedAreaById'](arg1);
}

export function GetProcessedAreasByDocumentId(arg1) {
  return window['go']['ipc']['Channel']['GetProcessedAreasByDocumentId'](arg1);
}

export function GetProjectByName(arg1) {
  return window['go']['ipc']['Channel']['GetProjectByName'](arg1);
}

export function GetSerializedContextGroups() {
  return window['go']['ipc']['Channel']['GetSerializedContextGroups']();
}

export function GetSupportedLanguages() {
  return window['go']['ipc']['Channel']['GetSupportedLanguages']();
}

export function GetUserMarkdownByDocumentId(arg1) {
  return window['go']['ipc']['Channel']['GetUserMarkdownByDocumentId'](arg1);
}

export function RequestAddArea(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestAddArea'](arg1, arg2);
}

export function RequestAddDocument(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestAddDocument'](arg1, arg2);
}

export function RequestAddDocumentGroup(arg1) {
  return window['go']['ipc']['Channel']['RequestAddDocumentGroup'](arg1);
}

export function RequestAddProcessedArea(arg1) {
  return window['go']['ipc']['Channel']['RequestAddProcessedArea'](arg1);
}

export function RequestChangeAreaOrder(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestChangeAreaOrder'](arg1, arg2);
}

export function RequestChangeGroupOrder(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestChangeGroupOrder'](arg1, arg2);
}

export function RequestChangeSessionProjectByName(arg1) {
  return window['go']['ipc']['Channel']['RequestChangeSessionProjectByName'](arg1);
}

export function RequestChooseUserAvatar() {
  return window['go']['ipc']['Channel']['RequestChooseUserAvatar']();
}

export function RequestConnectProcessedAreas(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestConnectProcessedAreas'](arg1, arg2);
}

export function RequestDeleteAreaById(arg1) {
  return window['go']['ipc']['Channel']['RequestDeleteAreaById'](arg1);
}

export function RequestDeleteDocumentAndChildren(arg1) {
  return window['go']['ipc']['Channel']['RequestDeleteDocumentAndChildren'](arg1);
}

export function RequestDeleteProcessedAreaById(arg1) {
  return window['go']['ipc']['Channel']['RequestDeleteProcessedAreaById'](arg1);
}

export function RequestDisconnectProcessedAreas(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestDisconnectProcessedAreas'](arg1, arg2);
}

export function RequestSaveContextGroupCollection() {
  return window['go']['ipc']['Channel']['RequestSaveContextGroupCollection']();
}

export function RequestSaveDocumentCollection() {
  return window['go']['ipc']['Channel']['RequestSaveDocumentCollection']();
}

export function RequestSaveGroupCollection() {
  return window['go']['ipc']['Channel']['RequestSaveGroupCollection']();
}

export function RequestSaveLocalUserProcessedMarkdownCollection() {
  return window['go']['ipc']['Channel']['RequestSaveLocalUserProcessedMarkdownCollection']();
}

export function RequestSaveProcessedTextCollection() {
  return window['go']['ipc']['Channel']['RequestSaveProcessedTextCollection']();
}

export function RequestTranslateArea(arg1) {
  return window['go']['ipc']['Channel']['RequestTranslateArea'](arg1);
}

export function RequestUpdateArea(arg1) {
  return window['go']['ipc']['Channel']['RequestUpdateArea'](arg1);
}

export function RequestUpdateCurrentUser(arg1) {
  return window['go']['ipc']['Channel']['RequestUpdateCurrentUser'](arg1);
}

export function RequestUpdateDocument(arg1) {
  return window['go']['ipc']['Channel']['RequestUpdateDocument'](arg1);
}

export function RequestUpdateDocumentUserMarkdown(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestUpdateDocumentUserMarkdown'](arg1, arg2);
}

export function RequestUpdateProcessedArea(arg1) {
  return window['go']['ipc']['Channel']['RequestUpdateProcessedArea'](arg1);
}

export function RequestUpdateProcessedWordById(arg1, arg2) {
  return window['go']['ipc']['Channel']['RequestUpdateProcessedWordById'](arg1, arg2);
}
