// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';

export function GetDocuments():Promise<ipc.GetDocumentsResponse>;

export function RequestAddDocument(arg1:string,arg2:string):Promise<ipc.Document>;

export function RequestAddDocumentGroup(arg1:string):Promise<ipc.DocumentGroup>;
